package com.wajtr.baf.features.product

import com.wajtr.baf.db.jooq.Tables
import com.wajtr.baf.db.jooq.tables.records.ProductRecord
import org.jooq.DSLContext
import org.springframework.stereotype.Repository
import org.springframework.transaction.annotation.Transactional
import java.math.BigDecimal
import java.util.*


/**
 * Represents product created by the company and offered for sale. Sales department is trying to sell
 * these products to customers.
 *
 * Related tables: public.product
 */
data class Product(
    var id: UUID?,
    var name: String,
    var price: BigDecimal,
    var description: String?
)


/**
 * Default implementation of the DAO.
 *
 * @author Bretislav Wajtr
 */
@Repository
@Transactional
class ProductRepository(
    private val context: DSLContext
) {

    private val mapIntoProduct = { record: ProductRecord ->
        Product(
            record.id,
            record.name,
            record.price,
            record.description
        )
    }

    fun findById(id: UUID): Product {
        return context
            .selectFrom(Tables.PRODUCT)
            .where(Tables.PRODUCT.ID.eq(id))
            .fetchOne(mapIntoProduct)!!
    }

    fun findAll(): List<Product> {
        return context
            .selectFrom(Tables.PRODUCT)
            .fetch(mapIntoProduct)
    }

    fun insert(input: Product) {
        val id = context.insertInto(Tables.PRODUCT)
            .set(Tables.PRODUCT.NAME, input.name)
            .set(Tables.PRODUCT.PRICE, input.price)
            .set(Tables.PRODUCT.DESCRIPTION, input.description)
            .returning(Tables.PRODUCT.ID)
            .fetchOne()!!
            .id

        input.id = id // set ID generated by database to model object
    }

    fun update(input: Product): Int {
        val record = ProductRecord()
        record.from(input)
        return context.executeUpdate(record)
    }

    fun deleteById(id: UUID): Int {
        return context.deleteFrom(Tables.PRODUCT).where(Tables.PRODUCT.ID.eq(id)).execute()
    }

    fun findByName(name: String): Product {
        return context.selectFrom(Tables.PRODUCT).where(Tables.PRODUCT.NAME.eq(name)).fetchOne(mapIntoProduct)!!
    }
}
