/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "baf"
include(":backend")
include(":ui")
project(":backend").projectDir = file("sources/backend")
project(":backend").name = "backend"
project(":ui").projectDir = file("sources/ui")
project(":ui").name = "ui"
