package com.wajtr.baf.core.tenants

import com.wajtr.baf.db.jooq.Tables.TENANT
import com.wajtr.baf.db.jooq.tables.records.TenantRecord
import org.jooq.DSLContext
import org.springframework.stereotype.Repository
import org.springframework.transaction.annotation.Transactional
import java.io.Serializable
import java.util.*

/**
 * @author Bretislav Wajtr
 */
@Repository
@Transactional
class TenantRepository(private val create: DSLContext) {

    fun findById(id: UUID): Tenant? {
        return create.selectFrom(TENANT)
            .where(TENANT.ID.eq(id))
            .fetchOneInto<Tenant?>(Tenant::class.java)
    }

    fun findAll(): List<Tenant> {
        return create
            .selectFrom<TenantRecord>(TENANT)
            .fetchInto<Tenant>(Tenant::class.java)
    }

    fun insert(tenant: Tenant) {
        val id = create
            .insertInto(TENANT)
            .set(TENANT.ORGANIZATION_NAME, tenant.organizationName)
            .set(TENANT.ORGANIZATION_ADDRESS, tenant.organizationAddress)
            .set(
                TENANT.ORGANIZATION_COUNTRY_CODE,
                tenant.organizationCountryCode
            )
            .returning(TENANT.ID)
            .fetchOne()!!
            .getId()

        tenant.id = id // set ID generated by database to model object
    }

    fun update(tenant: Tenant): Int {
        val record = TenantRecord()
        record.from(tenant)
        return create.executeUpdate(record)
    }

    fun deleteById(id: UUID): Int {
        return create.deleteFrom(TENANT).where(TENANT.ID.eq(id)).execute()
    }

    fun updateTenantMandatoryData(tenantId: UUID, tenantName: String, setupRequired: Boolean) {
        create.update(TENANT)
            .set(TENANT.SETUP_REQUIRED, setupRequired)
            .set(TENANT.ORGANIZATION_NAME, tenantName)
            .where(TENANT.ID.eq(tenantId))
            .execute()
    }
}


/**
 * Represents tenant, usually a company, which have access to the application.
 */
data class Tenant(
    var id: UUID?, // can be null if record not yet saved in database
    var organizationName: String,
    var organizationAddress: String?,
    var organizationCountryCode: String?,
    val setupRequired: Boolean
) : Serializable
