/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

// Add jOOQ generated sources directory
sourceSets {
    main {
        kotlin {
            srcDir("src/gen/jooq")
        }
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.cache)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.flyway)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.oauth2.client)
    api(libs.com.github.ben.manes.caffeine.caffeine)
    api(libs.org.flywaydb.flyway.core)
    api(libs.org.flywaydb.flyway.database.postgresql)
    api(libs.org.postgresql.postgresql)
    api(libs.org.springframework.boot.spring.boot.starter.jooq)
    api(libs.org.jooq.jooq.kotlin)
    api(libs.jakarta.validation.jakarta.validation.api)
    api(libs.net.sf.jasperreports.jasperreports)
    api(libs.net.logstash.logback.logstash.logback.encoder)
    api(libs.org.slf4j.jul.to.slf4j)
    api(libs.com.ibm.icu.icu4j)
    api(libs.commons.codec.commons.codec)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.boot.spring.boot.testcontainers)
    testImplementation(libs.org.testcontainers.testcontainers.postgresql)
    testImplementation(libs.org.testcontainers.testcontainers.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

description = "backend"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
