/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.vaadin)
}

dependencies {
    api(project(":backend"))
    api(libs.com.vaadin.vaadin.core)
    api(libs.com.vaadin.vaadin.dev)
    api(libs.com.vaadin.vaadin.spring.boot.starter)
    api(libs.com.github.mvysny.karibudsl.karibu.dsl.v23)
}

springBoot {
    mainClass.set("com.wajtr.baf.ApplicationMainKt")
}

description = "ui"
