/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    kotlin("jvm")
    kotlin("plugin.spring")
    id("io.spring.dependency-management")
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.vaadin.com/vaadin-addons")
    }
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.boot:spring-boot-dependencies:4.0.0") {
            bomProperty("postgresql.version", "42.7.7")
            bomProperty("flyway.version", "11.11.2")
            bomProperty("jooq.version", "3.20.7")
        }
    }
}

dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib:2.3.0")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.3.0")
    api("org.jetbrains.kotlin:kotlin-reflect:2.3.0")
    api("com.fasterxml.jackson.module:jackson-module-kotlin:2.20.1")
    //testImplementation("org.jetbrains.kotlin:kotlin-test:2.3.0")
}

group = "com.wajtr.baf"
version = "1.0.0-SNAPSHOT"

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType<Test>() {
    useJUnitPlatform()
}
